n1=float (input("Valor de x"))
n2=float (input("Valor de y"))
n3=float(input("Valor de Z"))
n4=float (input("Valor de f"))
result=(((n1*n1)+(2*n2)+n3-(4*n4))/2)
print("O resultado dda equação é: {:.2f}" .format(result))